"""改变了Favorite表结构

Revision ID: 4e14b70eac69
Revises: 837f7078562d
Create Date: 2018-04-29 20:47:21.125104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e14b70eac69'
down_revision = '837f7078562d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followfavorites',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('postfavorites',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'favorite_id')
    )
    op.create_table('questionfavorites',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'favorite_id')
    )
    op.create_table('answerfavorites',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('answer_id', 'favorite_id')
    )
    op.drop_table('followposts')
    op.add_column('answers', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.drop_constraint('answers_ibfk_2', 'answers', type_='foreignkey')
    op.drop_column('answers', 'favorite_id')
    op.add_column('favorites', sa.Column('answers_count', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('posts_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('tag_count', sa.Integer(), nullable=True))
    op.drop_constraint('posts_ibfk_2', 'posts', type_='foreignkey')
    op.drop_column('posts', 'favorite_id')
    op.add_column('questions', sa.Column('answers_count', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.drop_constraint('questions_ibfk_2', 'questions', type_='foreignkey')
    op.drop_column('questions', 'favorite_id')
    op.add_column('tags', sa.Column('post_count', sa.Integer(), nullable=True))
    op.add_column('topics', sa.Column('questions_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'questions_count')
    op.drop_column('tags', 'post_count')
    op.add_column('questions', sa.Column('favorite_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('questions_ibfk_2', 'questions', 'favorites', ['favorite_id'], ['id'])
    op.drop_column('questions', 'followers_count')
    op.drop_column('questions', 'comments_count')
    op.drop_column('questions', 'answers_count')
    op.add_column('posts', sa.Column('favorite_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_ibfk_2', 'posts', 'favorites', ['favorite_id'], ['id'])
    op.drop_column('posts', 'tag_count')
    op.drop_column('posts', 'comments_count')
    op.drop_column('favorites', 'posts_count')
    op.drop_column('favorites', 'followers_count')
    op.drop_column('favorites', 'comments_count')
    op.drop_column('favorites', 'answers_count')
    op.add_column('answers', sa.Column('favorite_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('answers_ibfk_2', 'answers', 'favorites', ['favorite_id'], ['id'])
    op.drop_column('answers', 'comments_count')
    op.create_table('followposts',
    sa.Column('follower_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('followed_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['favorites.id'], name='followposts_ibfk_1'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='followposts_ibfk_2'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('answerfavorites')
    op.drop_table('questionfavorites')
    op.drop_table('postfavorites')
    op.drop_table('followfavorites')
    # ### end Alembic commands ###
