"""话题添加封面图片

Revision ID: 80d3da091e28
Revises: ba701867201a
Create Date: 2018-05-01 11:29:35.940899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d3da091e28'
down_revision = 'ba701867201a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('cover_url', sa.String(length=128), nullable=True))
    op.add_column('topics', sa.Column('cover_url_sm', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'cover_url_sm')
    op.drop_column('topics', 'cover_url')
    # ### end Alembic commands ###
