"""change name of qt

Revision ID: 837f7078562d
Revises: d8aa0bd9523d
Create Date: 2018-04-28 21:17:20.509788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '837f7078562d'
down_revision = 'd8aa0bd9523d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questiontopics',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'question_id')
    )
    op.drop_table('question_topic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_topic',
    sa.Column('topic_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='question_topic_ibfk_1'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name='question_topic_ibfk_2'),
    sa.PrimaryKeyConstraint('topic_id', 'question_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('questiontopics')
    # ### end Alembic commands ###
